"""update documents model

Revision ID: 31b0b63350c6
Revises: f21988ccbe5a
Create Date: 2026-05-23 06:40:11.981760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b0b63350c6'
down_revision: Union[str, Sequence[str], None] = 'f21988ccbe5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('user_name', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('organization_name', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('created_at', sa.date(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('documents', sa.Column('start_at', sa.date(timezone=True), nullable=False))
    op.add_column('documents', sa.Column('end_at', sa.date(timezone=True), nullable=False))
    op.add_column('documents', sa.Column('status', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.drop_column('documents', 'content')
    op.drop_column('documents', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'end_at')
    op.drop_column('documents', 'start_at')
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'organization_name')
    op.drop_column('documents', 'user_name')
    # ### end Alembic commands ###
