"""update documents model field is_archived

Revision ID: 59300da9bad5
Revises: 264333645c64
Create Date: 2026-06-15 12:23:55.036190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59300da9bad5'
down_revision: Union[str, Sequence[str], None] = '264333645c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('documents', 'is_archived')
    # ### end Alembic commands ###
