"""add_refresh_token_hash_to_users

Revision ID: 97b779f56d9d
Revises: b6af56485812
Create Date: 2026-06-26 14:28:52.505106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97b779f56d9d'
down_revision: Union[str, Sequence[str], None] = 'b6af56485812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_hash')
    # ### end Alembic commands ###
